### ISSUE TITLE
SettingActivity의 Preference 때문에 애먹고 있습니다.

### ISSUE THREAD

**Issue by jjangg96** [bw-moon/JaramAndroid#3]
참 어렵네요.
SettingActivity가 PreferenceScreen를 사용하고 있어서 xml과 약간의 코드로 깔끔하게 설정할 수 있는 부분이 좋긴한데 커스터마이즈가 너무 힘듭니다.
현재 Manifest를 보면 min이 8이라서 SwitchPreference를 사용할 수 없네요. API 14부터 지원 가능하네요.

XML, PrefenceScreen 버리고 커스텀 뷰로 가는게 어떨까요?

**Comment by bw-moon** [comment]
난 그렇게 가도 좋다고 생각하는데, 내가 PreferenceScreen을 사용한건, 인터넷 검색해본 결과로 나온거라서.
커밋하면 반영해줄께.
