### ISSUE TITLE
MyLyn 연동 테스트

### ISSUE THREAD

**Issue by cloudeyes** [bw-moon/JaramAndroid#4]
# 개요

이클립스로 clone한 프로젝트 실행해 보고 MyLyn 으로 이슈 작성 해보는 테스트 해 보고 있습니다.
안드로이드는 한 2년 전에 Hello World 정도의 간단한 앱만 만들어보고 진지하게 해 본적 없는데 에뮬레이터가 참 구리다 라는 강한 인상이 남아있었죠. 
여전히 에뮬레이터는 구리군요... (xcode 보고 배워라 이놈들아...)

원래 MyLyn 으로 스크린 캡쳐도 가능한데. 이클립스 플러그인은 그게 안되는 듯 하고. 많이 낯서네요.

MyLyn 연동을 위해서는 MarketPlace에서 GitHub 플러그인을 설치하고, 아래 URL 로 Repository를 만들면 됩니다.
- https://github.com/ByeongweonMoon/JaramAndroid/issues
# 스크린샷 만드는 팁

여기 괜찮네요: http://snag.gy
크롬이나 파이어 폭스로 들어가서 그림 캡쳐한 담에 Ctrl+V 로 마치 가상의 클립보드 처럼 붙여넣기가 가능합니다.
그 담엔 아래와 같이 그림 첨부하면 됩니다.

`![에뮬레이터 스크린샷](http://snag.gy/eOJQA.jpg)`

![에뮬레이터 스크린샷](http://snag.gy/eOJQA.jpg)

**Comment by bw-moon** [comment]
오 좋네요. ^^

**Comment by cloudeyes** [comment]
snag.gy 좋지요?

이슈 트래킹... MyLyn 으로 만든 이슈(태스크)에 포커스 걸어놓고 작업 하면 집중도 되고 관련 소스들이 IDE 에서 자동으로 묶이고 변경점도 관리해줘서 무지 좋지요...
스샷 첨부 못하는게 안습... 플러그인좀 개선해줬으면 좋겠네... 

에뮬레이터는 못 써먹겠어서 내 갤탭 USB로 연결해서 하던가 해야겠다. 에뮬레이터가 느려서 실기를 꽃아서 해야만 한다는 건... 소프트웨어 공학 관점에서 테스트에 너무 취약한거 아닌가 싶네... 해상도나 CPU/MEM 등 환경이 실기에 종속되어 버리니... 안그래도 Fragment 가 대단한 안드로이드 플랫폼인데...

내 PC i5 2500 / SSD 830 / Mem 4G 임 ... 여기보다 사양 낮은 컴(회사컴) 에서도 xcode 아이폰 시뮬레이터 (심지어는 vmware에 서 돌리는데도!!!)  팍팍 뜨고 엄청 부드럽게 돌아가거든...

**Comment by bw-moon** [comment]
전 그래서 에뮬 안쓰고 그냥 휴대폰으로 개발합니다..
느려요..

2012년 11월 2일 오전 10:42, YongKi Kim notifications@github.com님의 말:

> snag.gy 좋지요?
> 
> 이슈 트래킹... MyLyn 으로 만든 이슈(태스크)에 포커스 걸어놓고 작업 하면 집중도 되고 관련 소스들이 IDE 에서 자동으로
> 묶이고 변경점도 관리해줘서 무지 좋지요...
> 스샷 첨부 못하는게 안습... 플러그인좀 개선해줬으면 좋겠네...
> 
> 에뮬레이터는 못 써먹겠어서 내 갤탭 USB로 연결해서 하던가 해야겠다. 에뮬레이터가 느려서 실기를 꽃아서 해야만 한다는 건...
> 소프트웨어 공학 관점에서 테스트에 너무 취약한거 아닌가 싶네... 해상도나 CPU/MEM 등 환경이 실기에 종속되어 버리니...
> 안그래도 Fragment 가 대단한 안드로이드 플랫폼인데...
> 
> 내 PC i5 2500 / SSD 830 / Mem 4G 임 ... 여기보다 사양 낮은 컴에서도 xcode 아이폰 시뮬레이터
> (심지어는 vmware에 서 돌리는데도!!!) 팍팍 뜨고 엄청 부드럽게 돌아가거든...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ByeongweonMoon/JaramAndroid/issues/4#issuecomment-10002479.

## 

Byeongweon Moon
http://tasy.jaram.org/blog

**Comment by cloudeyes** [comment]
/close
이게 몇년만인지~ ... Github 이슈 리스트에 있는거 Close 해요~
즐거운 봄날 보내길... ㅎㅎ
